spring:
  profiles: local, default
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 6265

eureka:
  client:
    enabled: false

security:
  oauth2:
    authorization:
      jwt:
        keyValue: somereallylongsigningkey
    client:
      client-id: cobra
      client-secret: bdzVzgIh39udscWyyuKiywAtyYp7uxtz
      scope: all
    resource:
      user-info-uri: http://localhost:6265/user/me
---
spring:
  profiles: cloud

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.cobra-authentication-server.credentials.url}

security:
  oauth2:
    resource:
      token-info-uri: https://cobra-authentication-server.cfapps.io/oauth/check_token
    client:
      client-id: cobra
      client-secret: bdzVzgIh39udscWyyuKiywAtyYp7uxtz